# Generated by Django 5.0.2 on 2024-03-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_taskmodel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
