# Generated by Django 5.0.2 on 2024-02-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Mystery', 'Mystery'), ('Thriller', 'Thiller'), ('Sci-fi', 'Sci-fi'), ('Humor', 'Humor'), ('Horror', 'Horror')], max_length=30)),
                ('last_pub', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
