# Generated by Django 5.0.2 on 2024-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookstoremodel_first_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='first_pub',
            field=models.DateField(auto_now_add=True),
        ),
    ]
