# Generated by Django 5.0.2 on 2024-02-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_studentinfomodel_teacherinfomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfoModel',
        ),
        migrations.DeleteModel(
            name='TeacherInfoModel',
        ),
    ]
